theme: jekyll-theme-minimal
logo: portrait.png
google_analytics: UA-9578462-2
title: Amirhossein Hajigholam-Saryazdi
description: Data Scientist and Business Analyst | SAS Certified Specialist (Canada)


